# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/CaesarCipher.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PATH'] = "../platforms"


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(994, 666)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_Title = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Title.setGeometry(QtCore.QRect(310, 40, 421, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Title.setFont(font)
        self.lbl_Title.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lbl_Title.setObjectName("lbl_Title")
        self.lbl_Plain = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Plain.setGeometry(QtCore.QRect(60, 180, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lbl_Plain.setFont(font)
        self.lbl_Plain.setObjectName("lbl_Plain")
        self.lbl_Key = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Key.setGeometry(QtCore.QRect(50, 270, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lbl_Key.setFont(font)
        self.lbl_Key.setObjectName("lbl_Key")
        self.lbl_Cipher = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Cipher.setGeometry(QtCore.QRect(50, 370, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lbl_Cipher.setFont(font)
        self.lbl_Cipher.setObjectName("lbl_Cipher")
        self.txt_PlainText = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_PlainText.setGeometry(QtCore.QRect(280, 160, 691, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txt_PlainText.setFont(font)
        self.txt_PlainText.setObjectName("txt_PlainText")
        self.txt_Key = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_Key.setGeometry(QtCore.QRect(280, 270, 691, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_Key.setFont(font)
        self.txt_Key.setObjectName("txt_Key")
        self.txt_CipherText = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_CipherText.setGeometry(QtCore.QRect(280, 360, 691, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_CipherText.setFont(font)
        self.txt_CipherText.setObjectName("txt_CipherText")
        self.btn_Encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Encrypt.setGeometry(QtCore.QRect(230, 510, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Encrypt.setFont(font)
        self.btn_Encrypt.setObjectName("btn_Encrypt")
        self.btn_Decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Decrypt.setGeometry(QtCore.QRect(670, 510, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Decrypt.setFont(font)
        self.btn_Decrypt.setObjectName("btn_Decrypt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 994, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_Title.setText(_translate("MainWindow", "CAESAR CIPHER"))
        self.lbl_Plain.setText(_translate("MainWindow", "Plain text:"))
        self.lbl_Key.setText(_translate("MainWindow", "Key"))
        self.lbl_Cipher.setText(_translate("MainWindow", "Cipher text:"))
        self.btn_Encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btn_Decrypt.setText(_translate("MainWindow", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
